### ISSUE TITLE
Migration Bumps errors

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-django-mongo#2]
Hello @b3nhard 

The migration is not successful. here is the LOG: 

The problem seems to be at Django/MongoDB driver level. 

Please take a look and advise. 

Ty! 

*** *** *** *** 

```log
(env) PS D:\work\repo-boilerplates\api-server-django-mongo> python.exe .\manage.py migrate
Operations to perform:
  Apply all migrations: admin, api_authentication, api_user, auth, contenttypes, sessions
Running migrations:
This version of djongo does not support "NULL, NOT NULL column validation check" fully. Visit https://nesdis.github.io/djongo/support/
  Applying contenttypes.0001_initial...This version of djongo does not support "schema validation using CONSTRAINT" fully. Visit https://nesdis.github.io/djongo/support/
 OK
  Applying contenttypes.0002_remove_content_type_name...This version of djongo does not support "COLUMN DROP NOT NULL " fully. Visit https://nesdis.github.io/djongo/support/
This version of djongo does not support "DROP CASCADE" fully. Visit https://nesdis.github.io/djongo/support/
Traceback (most recent call last):
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\djongo\sql2mongo\query.py", line 857, in parse
    return handler(self, statement)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\djongo\sql2mongo\query.py", line 894, in _alter
    query.execute()
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\djongo\sql2mongo\query.py", line 533, in _drop_column
    self.db[self.left_table].update(
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\pymongo\collection.py", line 3213, in __call__
    raise TypeError(
TypeError: 'Collection' object is not callable. If you meant to call the 'update' method on a 'Collection' object it is failing because no such method exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\djongo\cursor.py", line 51, in execute
    self.result = Query(
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\djongo\sql2mongo\query.py", line 784, in __init__
    self._query = self.parse()
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\djongo\sql2mongo\query.py", line 885, in parse
    raise exe from e
djongo.exceptions.SQLDecodeError:

        Keyword: None
        Sub SQL: None
        FAILED SQL: ALTER TABLE "django_content_type" DROP COLUMN "name" CASCADE
        Params: ()
        Version: 1.3.6

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\core\management\commands\migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\migrations\executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\migrations\migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\migrations\operations\fields.py", line 170, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\backends\base\schema.py", line 559, in remove_field
    self.execute(sql)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\backends\base\schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\core\management\base.py", line 367, in run_from_argv
    connections.close_all()
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\utils.py", line 213, in close_all
    connection.close()
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\django\db\backends\base\base.py", line 294, in close
    self._close()
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\djongo\base.py", line 208, in _close
    if self.connection:
  File "D:\work\repo-boilerplates\api-server-django-mongo\env\lib\site-packages\pymongo\database.py", line 1161, in __bool__
    raise NotImplementedError(
NotImplementedError: Database objects do not implement truth value testing or bool(). Please compare with None instead: database is not None
(env) PS D:\work\repo-boilerplates\api-server-django-mongo>
```

**Comment by b3nhard** [comment]
Can i get the version of MongoDB you are running?

**Comment by admin-dashboards** [comment]
Here is the shot

*** *** *** *** 
![image](https://user-images.githubusercontent.com/51854817/205245654-22aca327-adf5-412e-ba21-71f1d6477d4b.png)

**Comment by b3nhard** [comment]
Using MongoDb with django it doesn't require migrations to be done unlike SQL databases

**Comment by app-generator** [comment]
ok. let me test.
TY @b3nhard

**Comment by app-generator** [comment]
This can be closed.

**Comment by app-generator** [comment]
validated. ty @b3nhard
